batch_size: 1                  # batch size
fine_tune_from: pretrained_gin  # pretrained_gcn/pretrained_gin
gpu: cpu                        # training GPU

model_type: gin                 # GNN backbone (i.e., gcn/gin)
model:
  num_layer: 5                  # number of graph conv layers
  emb_dim: 300                  # embedding dimension in graph conv layers
  feat_dim: 512                 # output feature dimention
  pool: mean                    # readout pooling (i.e., mean/max/add)